// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// findThresholdAIMER
Rcpp::List findThresholdAIMER(arma::mat X, arma::colvec y, arma::colvec ncomps, arma::colvec nCovs, int nthresh, int kfold);
RcppExport SEXP aimer_findThresholdAIMER(SEXP XSEXP, SEXP ySEXP, SEXP ncompsSEXP, SEXP nCovsSEXP, SEXP nthreshSEXP, SEXP kfoldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type nCovs(nCovsSEXP);
    Rcpp::traits::input_parameter< int >::type nthresh(nthreshSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    rcpp_result_gen = Rcpp::wrap(findThresholdAIMER(X, y, ncomps, nCovs, nthresh, kfold));
    return rcpp_result_gen;
END_RCPP
}
// AIMER
arma::colvec AIMER(arma::mat X, arma::colvec y, double nCovs, double b, int nComps);
RcppExport SEXP aimer_AIMER(SEXP XSEXP, SEXP ySEXP, SEXP nCovsSEXP, SEXP bSEXP, SEXP nCompsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type nCovs(nCovsSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nComps(nCompsSEXP);
    rcpp_result_gen = Rcpp::wrap(AIMER(X, y, nCovs, b, nComps));
    return rcpp_result_gen;
END_RCPP
}
// findThresholdSel
Rcpp::List findThresholdSel(arma::mat X, arma::colvec y, arma::colvec ncomps, arma::colvec nCovs, int nthresh, int kfold, arma::colvec nCovsSelect, int nthreshSelect);
RcppExport SEXP aimer_findThresholdSel(SEXP XSEXP, SEXP ySEXP, SEXP ncompsSEXP, SEXP nCovsSEXP, SEXP nthreshSEXP, SEXP kfoldSEXP, SEXP nCovsSelectSEXP, SEXP nthreshSelectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type nCovs(nCovsSEXP);
    Rcpp::traits::input_parameter< int >::type nthresh(nthreshSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type nCovsSelect(nCovsSelectSEXP);
    Rcpp::traits::input_parameter< int >::type nthreshSelect(nthreshSelectSEXP);
    rcpp_result_gen = Rcpp::wrap(findThresholdSel(X, y, ncomps, nCovs, nthresh, kfold, nCovsSelect, nthreshSelect));
    return rcpp_result_gen;
END_RCPP
}
