#'predicts new values for an aimer model.
#'
#'@param object required, a model generated by the aimer function.
#'@param newdata required, a new data matrix to predict with.
#'
#'@return predicted value vector of length nrow(newdata).
#'
#'@export
predict.aimer <- function(object, newdata, ...){
    newdata = as.matrix(newdata)
    newdata = scale(newdata, scale = FALSE)
    indeces = object$beta != 0
    newdata[,indeces] %*% object$beta[indeces]
}




#'predicts new values for an aimerCV model.
#'
#'@param object required, a model generated by the aimerCV function.
#'@param newdata required, a new data matrix to predict with.
#'
#'@return predicted value vector of length nrow(newdata).
#'
#'@export
predict.aimerCV <- function(object, newdata, ...){
    predict.aimer(object, newdata)
}



#'returns the fitted values of an aimer model.
#'
#'@param object required, an aimer model.
#'
#'@return fitted values of the original data (vector of length n).
#'
#'@export
fitted.aimer <- function(object, ...){
    object$fitted
}

#'returns the fitted values of an aimerCV model.
#'
#'@param object required, an aimerCV model.
#'
#'@return fitted values of the original data (vector of length n).
#'
#'@export
fitted.aimerCV <- function(object, ...){
    object$fitted
}

#'returns the residuals of an aimer model.
#' 
#'@param object required, an aimer model.
#'
#'@return residuals of the original data (vector of length n).
#'
#'@export
residuals.aimer <- function(object, ...){
    object$residuals
}


#'returns the residuals of an aimerCV model.
#' 
#'@param object required, an aimerCV model.
#'
#'@return residuals of the original data (vector of length n).
#'
#'@export
residuals.aimerCV <- function(object, ...){
    object$residuals
}




#'returns the coefficients of an aimer model.
#'
#'@param object required, an aimer model.
#'
#'@return coefficient vector for the model
#'
#'@export
coefficients.aimer <- function(object, ...){
    object$beta
}



#'returns the coefficients of an aimerCV model.
#'
#'@param object required, an aimerCV model.
#'
#'@return coefficient vector for the model
#'
#'@export
coefficients.aimerCV <- function(object, ...){
    object$beta
}


#'plots the residuals in terms of the fitted values for an aimer model
#'
#'@param object required, an aimer model.
#'
#'@return void.
#'
#'@export
plot.aimer <- function(object, ...){
    plot(object$residuals ~ object$fitted, xlab = "fitted values", ylab = "residuals")
}

#'creates a heatmap of each value of ncomps tested in an aimerCV model
#'
#'@param object required, an aimerCV model.
#'
#'@return void.
#'
#'@export
plot.aimerCV <- function(object, ...){
    original = par(ask = TRUE)
    ggplot2::ggplot(ggplot2::aes(x = object$ncomps, y = object$nCovs) +
                    ggplot2::geom_tile(ggplot2::aes(fill = object$mse[object$nCovs.select == object$nCov.select.best,,])))
#    image(x = object$ncomps, y = object$nCovs, 
#          z = object$mse[object$nCovs.select == object$nCov.select.best,,], 
#          xlab = "ncomps", ylab = "ncovs", main = "for optimal value of nCovs.select")
#    image(x = object$nCovs.select, y = object$ncomps, 
#          z = object$mse[,,object$nCovs == object$nCov.best], 
#          xlab = "nCovs.select", ylab = "ncomps", main = "for optimal value of nCovs")
#    image(x = object$nCovs.select, y = object$nCovs, 
#          z = object$mse[,object$ncomps == object$ncomp.best,], 
#          xlab = "nCovs.select", ylab = "nCovs", main = "for optimal value of ncomps")
    par(original)
}